films/urls.py
from django.urls import path
from . import views

app_name = 'films'

urlpatterns = [
    path('', views.home_page, name='home'),
    path('filter/', views.filter_films, name='filter_films'),
    path('<slug:category_slug>', views.film_list_category, name='films_catalog_category'),
    path('genre/<int:pk>/<str:slug>', views.film_list_genre, name='films_catalog_genre'),
    path('review/<slug:film_slug>/', views.add_review_or_comment, name='add_review'),
    path('search-result/', views.search_result, name='search_result'),
    path('film/<slug:film_slug>', views.detail_page, name='detail_page'),
    path('about/', views.about_page, name='about'),
    path('contacts/', views.contact_page, name='contacts'),
    path('privacy/', views.privacy_page, name='privacy_policy'),
    path('delete-comment/<int:pk>/<str:slug>', views.delete_comment, name='delete_comment'),
    path('delete_review/<int:pk>/<str:slug>', views.delete_review, name='delete_review'),
    path('like_comment/', views.comments_likes_or_dislike, name='like_unlike_comment'),
    path('like_review/', views.review_likes_or_dislike, name='like_unlike_review'),
    path('selected/', views.selected_movie, name='selected_movie'),
]

portfolio_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="Photo API",
        default_version="v1",
        description="Displaying Movies from authorsFilmsFlixGo portfolio",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="kirkevich.anton@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny, ],
)


urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('api/v1/', include('apimovie.urls')),
    path('api/v1/dj-rest-auth/', include('dj_rest_auth.urls')),
    path('api/v1/dj-rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path("", include("films.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/pages/about.html
{% extends 'base.html' %}
{% block title %}About{% endblock title %}
{% block content %}
	<!-- page title -->
	<section class="section section--first section--bg">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="section__wrap">
						<!-- section title -->
						<h2 class="section__title">About Us</h2>
						<!-- end section title -->

						<!-- breadcrumb -->
						<ul class="breadcrumb">
							<li class="breadcrumb__item"><a href="{% url 'films:home' %}">Home</a></li>
							<li class="breadcrumb__item breadcrumb__item--active">About Us</li>
						</ul>
						<!-- end breadcrumb -->
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- end page title -->

	<!-- about -->
	<section class="section">
		<div class="container">
			<div class="row">
				<!-- section title -->
				<div class="col-12">
					<h2 class="section__title"><b>AFFG</b> – Best Place for Movies</h2>
				</div>
				<!-- end section title -->

				<!-- section text -->
				<div class="col-12">
					<p class="section__text">It is a long <b>established</b> fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using.</p>

					<p class="section__text section__text--last-with-margin">'Content here, content here', making it look like English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>
				</div>
				<!-- end section text -->

				<!-- feature -->
				<div class="col-12 col-md-6 col-lg-4">
					<div class="feature">
						<i class="icon ion-ios-tv feature__icon"></i>
						<h3 class="feature__title">Ultra HD</h3>
						<p class="feature__text">If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.</p>
					</div>
				</div>
				<!-- end feature -->

				<!-- feature -->
				<div class="col-12 col-md-6 col-lg-4">
					<div class="feature">
						<i class="icon ion-ios-film feature__icon"></i>
						<h3 class="feature__title">Film</h3>
						<p class="feature__text">All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first.</p>
					</div>
				</div>
				<!-- end feature -->

				<!-- feature -->
				<div class="col-12 col-md-6 col-lg-4">
					<div class="feature">
						<i class="icon ion-ios-trophy feature__icon"></i>
						<h3 class="feature__title">Awards</h3>
						<p class="feature__text">It to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining.</p>
					</div>
				</div>
				<!-- end feature -->

				<!-- feature -->
				<div class="col-12 col-md-6 col-lg-4">
					<div class="feature">
						<i class="icon ion-ios-notifications feature__icon"></i>
						<h3 class="feature__title">Notifications</h3>
						<p class="feature__text">Various versions have evolved over the years, sometimes by accident, sometimes on purpose.</p>
					</div>
				</div>
				<!-- end feature -->

				<!-- feature -->
				<div class="col-12 col-md-6 col-lg-4">
					<div class="feature">
						<i class="icon ion-ios-rocket feature__icon"></i>
						<h3 class="feature__title">Rocket</h3>
						<p class="feature__text">It to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting.</p>
					</div>
				</div>
				<!-- end feature -->

				<!-- feature -->
				<div class="col-12 col-md-6 col-lg-4">
					<div class="feature">
						<i class="icon ion-ios-globe feature__icon"></i>
						<h3 class="feature__title">Multi Language Subtitles </h3>
						<p class="feature__text">Various versions have evolved over the years, sometimes by accident, sometimes on purpose.</p>
					</div>
				</div>
				<!-- end feature -->
			</div>
		</div>
	</section>
	<!-- end about -->

	<!-- how it works -->
	<section class="section section--dark">
		<div class="container">
			<div class="row">
				<!-- section title -->
				<div class="col-12">
					<h2 class="section__title section__title--no-margin">How it works?</h2>
				</div>
				<!-- end section title -->

				<!-- how box -->
				<div class="col-12 col-md-6 col-lg-4">
					<div class="how">
						<span class="how__number">01</span>
						<h3 class="how__title">Watch any movie</h3>
						<p class="how__text">It has never been an issue to find an old movie or TV show on the internet. However, this is not the case with the new releases.</p>
					</div>
				</div>
				<!-- ebd how box -->

				<!-- how box -->
				<div class="col-12 col-md-6 col-lg-4">
					<div class="how">
						<span class="how__number">02</span>
						<h3 class="how__title">Discuss in comments</h3>
						<p class="how__text">It has never been an issue to find an old movie or TV show on the internet. However, this is not the case with the new releases.</p>
					</div>
				</div>
				<!-- ebd how box -->

				<!-- how box -->
				<div class="col-12 col-md-6 col-lg-4">
					<div class="how">
						<span class="how__number">03</span>
						<h3 class="how__title">Set rating for Movie</h3>
						<p class="how__text">It has never been an issue to find an old movie or TV show on the internet. However, this is not the case with the new releases.</p>
					</div>
				</div>
				<!-- ebd how box -->
			</div>
		</div>
	</section>
	<!-- end how it works -->

	<!-- partners -->
	{% include 'include/partners.html' %}
	<!-- end partners -->

	<!-- footer -->
{% endblock content %}

templates/pages/contacts.html
{% extends 'base.html' %}
{% block title %}Contacts{% endblock title %}
{% load social_share %}

{% block content %}
        <style>
    /* Popup form */
.popup__overlay{
	opacity: 0;
    visibility: hidden;
    width: 100%;
	height: 100%;
    position: fixed;
    top: 0;
    bottom: 0;
    background-color: rgba(0, 0, 0, 0.8);
    z-index: 20;
    opacity: 0;
    visibility: hidden;
    overflow-y: auto;
    overflow-x: hidden;
    -webkit-transition: all 0.2s ease-in-out;
    -moz--transition: all 0.2s ease-in-out;
    transition: all 0.2s ease-in-out;
}
.popup__overlay.active{
    opacity: 1;
    visibility: visible;
}
.bg-modal{
	transform: translateY(-100%);
    width: 100%;
    min-height: 100%;
    display: flex;
	justify-content: center;
    align-items: center;
    transform: translateY(-100%);
    -webkit-transition: all 0.4s ease-in-out;
    -moz--transition: all 0.4s ease-in-out;
    transition: all 0.4s ease-in-out;
}
.popup__overlay.active .bg-modal{
    transform: translateY(0);
}
.popup__container{
    {#padding: 70px;#}
    display: block;
    {#max-width: 600px;#}
    width: 100%;
    /*background-color: #1e2427;*/
}
.popup__container-inner{
    position: relative;
    margin: 70px;
	max-width: 417px;
	margin: 0 auto;
	text-align: center;
}

    </style>
	<!-- page title -->
	<section class="section section--first section--bg">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="section__wrap">
						<!-- section title -->
						<h2 class="section__title">Contacts</h2>
						<!-- end section title -->

						<!-- breadcrumb -->
						<ul class="breadcrumb">
							<li class="breadcrumb__item"><a href="{% url 'films:home' %}">Home</a></li>
							<li class="breadcrumb__item breadcrumb__item--active">Contacts</li>
						</ul>
						<!-- end breadcrumb -->
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- end page title -->

	<!-- contacts -->
	<section class="section">
		<div class="container">
			<div class="row">
				<div class="col-12 col-md-7 col-lg-8">
					<div class="row">
						<!-- section title -->
						<div class="col-12">
							<h2 class="section__title">Contact Form</h2>
						</div>
						<!-- end section title -->

						<div class="col-12">
							<form onsubmit="ContactFormSubmit(event)" id="form_to__reset" action="{% url 'films:contacts' %}" method="post" class="form form--contacts">
                                {% csrf_token %}
								<input id="contact__form_name" name="name" type="text" class="form__input" placeholder="Your Name" required>
								<input id="contact__form_email" name="email" type="text" class="form__input" placeholder="Email" required>
								<input id="contact__form_subject" name="subject" type="text" class="form__input" placeholder="Subject" required>
								<textarea id="contact__form_text" name="text" id="text" name="text" class="form__textarea" placeholder="Type your message..." required></textarea>
								<button type="submit" class="form__btn">Send</button>
							</form>
						</div>
					</div>
				</div>
				
				<div class="col-12 col-md-5 col-lg-4">
					<div class="row">
						<!-- section title -->
						<div class="col-12">
							<h2 class="section__title">Info</h2>
						</div>
						<!-- end section title -->

						<div class="col-12">
							<p class="section__text">It is a long fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using.</p>

							<ul class="contacts__list">
								<li><a href="tel:+18002345678">+1 800 234-5678</a></li>
								<li><a href="mailto:support@moviego.com">authorsfilmsflixgo@gmail.com</a></li>
							</ul>
							<ul class="contacts__social">
								<li class="facebook"><a href="{% post_to_facebook_url %}"><i class="icon ion-logo-facebook"></i></a></li>
						        <li class="twitter"><a href="{% post_to_twitter_url "Nice web site" %}"><i class="icon ion-logo-twitter"></i></a></li>
							</ul>
						</div>
					</div>
				</div>

			</div>
		</div>
	</section>
	<!-- end contacts -->
    <!-- popUP -->
    <div class="register__popup popup__overlay">
        <div class="popups bg-modal">
            <div class="popup__container">
                <div class="wrapper">
                    <div class="popup__container-inner">

                        <!--content-->
                        <form action="" class="sign__form" method="post">
                            {% csrf_token %}
                                <span class="sign__text"><h1 id="text__to_update" class="page-">
                                </h1></span>
                                <p style="margin-bottom: 0px;" id="lover_text__to_update" class="page-404__text">
                                </p>
                                <div class="row">
                                    <button type="button" name="comment_button" class="form__btn close__popup">Close</button>
{#                                    <div class="col-xs-6"><a href="{{ film.get_absolute_url }}" class="page-404__btn">Close</a></div>#}
{#                                    <div class="col-xs-6"><button class="page-404__btn" type="submit">&nbsp;Go Back&nbsp;</button></div>&nbsp&nbsp#}

                                </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end popUP -->
    <script>
        /*Popup*/
const popups = document.querySelectorAll(".popups");
const close_popup = document.querySelectorAll('.close__popup');

function openPopup(element, contactInfo){
        const popupWindow = document.querySelector('.register__popup');
        document.querySelector('#text__to_update').innerText = `Dear ${contactInfo[0]}`
        document.querySelector('#lover_text__to_update').innerHTML = `<span class="sign__text">Your information was send, and we will send our respond to your email: ${contactInfo[1]}</span></p>`;
        if(popupWindow){
            closePopup(popupWindow);
        }
}

if(close_popup.length > 0){
    for(let i = 0; i < close_popup.length; i++){
        const close_pop = close_popup[i];
        close_pop.addEventListener("click", function(e) {
            e.preventDefault();
            closePopup();
        });
    }
}

function closePopup(popupWindow){
    const popupOverlayAll = document.querySelectorAll('.popup__overlay');
    if(popupOverlayAll.length > 0){
        for(let i = 0; i < popupOverlayAll.length; i++){
            const popupOverlay = popupOverlayAll[i];
            popupOverlay.classList.remove('active');
        }
    }

    if(popupWindow){
        popupWindow.classList.add('active');
        {#document.getElementsByTagName("body")[0].style.overflow = "hidden";#}
    }
}


    function ContactFormSubmit(event){
            event.preventDefault();
            let contact_name = document.getElementById('contact__form_name').value;
            let contact_email = document.getElementById('contact__form_email').value;
            let contact_subject = document.getElementById('contact__form_subject').value;
            let contact_text = document.getElementById('contact__form_text').value;
            $.ajax({
                type: 'POST',
                url: '{% url "films:contacts" %}',
                data: {
                    name: contact_name,
                    email: contact_email,
                    subject: contact_subject,
                    text: contact_text,
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                    action: 'post'
                },
                success: function (json){
                    let formReset = document.getElementById('form_to__reset');
                    let contactInfo = [contact_name, contact_email];
                    openPopup(this, contactInfo);
                    formReset.reset();
                }
            })
        }


    </script>

	<!-- footer -->
{% endblock content %}

templates/pages/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}AFFG Home{% endblock title %}

{% block content %}
	<!-- home -->
	<section class="home">
		<!-- home bg -->
		<div class="owl-carousel home__bg">
			<div class="item home__cover" data-bg="{% static 'img/home/home__bg.jpg' %}"></div>
			<div class="item home__cover" data-bg="{% static 'img/home/home__bg2.jpg' %}"></div>
			<div class="item home__cover" data-bg="{% static 'img/home/home__bg3.jpg' %}"></div>
			<div class="item home__cover" data-bg="{% static 'img/home/home__bg4.jpg' %}"></div>
		</div>
		<!-- end home bg -->

		<div class="container">
			<div class="row">
				<div class="col-12">
					<h1 class="home__title"><b>OUR EDITORS CHOICE</b> OF THIS SEASON</h1>

					<button class="home__nav home__nav--prev" type="button">
						<i class="icon ion-ios-arrow-round-back"></i>
					</button>
					<button class="home__nav home__nav--next" type="button">
						<i class="icon ion-ios-arrow-round-forward"></i>
					</button>
				</div>
                <!-- movies start -->

				<div class="col-12">
					<div class="owl-carousel home__carousel">
                        {% for e_movie in editor_choice %}
                            <div class="item">
                                <!-- card -->
                                <div class="card card--big">
                                    <div class="card__cover">
                                        <img src="{{ e_movie.poster.url }}" alt="">
                                        <a href="{{ e_movie.get_absolute_url }}" class="card__play">
                                            <i class="icon ion-ios-play"></i>
                                        </a>
                                    </div>
                                    <div class="card__content">
                                        <h3 class="card__title"><a href="{{ e_movie.get_absolute_url }}">{{ e_movie.title }}</a></h3>
                                        <span class="card__category">
                                            {% for genre in e_movie.genre.all %}
                                                <a href="{% url 'films:films_catalog_genre' genre.id e_movie.category.slug %}">{{ genre.title }}</a>
                                            {% endfor %}
                                        </span>
                                        <span class="card__rate"><i class="icon ion-ios-star"></i>{{ e_movie.get_average_rating }}</span>
                                    </div>
                                </div>
                                <!-- end card -->
                            </div>
                        {% endfor %}
				</div>
			</div>
		</div>

    </section>
	<!-- end home -->

	<!-- content -->
	<section class="content">
		<div class="content__head">
			<div class="container">
				<div class="row">
					<div class="col-12">
						<!-- content title -->
						<h2 class="content__title">New items</h2>
						<!-- end content title -->

						<!-- content tabs nav -->
						<ul class="nav nav-tabs content__tabs" id="content__tabs" role="tablist">
							<li class="nav-item">
								<a class="nav-link active" data-toggle="tab" href="#tab-1" role="tab" aria-controls="tab-1" aria-selected="true">MOVIES</a>
							</li>

							<li class="nav-item">
								<a class="nav-link" data-toggle="tab" href="#tab-2" role="tab" aria-controls="tab-2" aria-selected="false">short film</a>
							</li>

							<li class="nav-item">
								<a class="nav-link" data-toggle="tab" href="#tab-3" role="tab" aria-controls="tab-3" aria-selected="false">documentaries</a>
							</li>

							<li class="nav-item">
								<a class="nav-link" data-toggle="tab" href="#tab-4" role="tab" aria-controls="tab-4" aria-selected="false">CARTOONS</a>
							</li>
						</ul>
						<!-- end content tabs nav -->

						<!-- content mobile tabs nav -->
						<div class="content__mobile-tabs" id="content__mobile-tabs">
							<div class="content__mobile-tabs-btn dropdown-toggle" role="navigation" id="mobile-tabs" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								<input type="button" value="New items">
								<span></span>
							</div>

							<div class="content__mobile-tabs-menu dropdown-menu" aria-labelledby="mobile-tabs">
								<ul class="nav nav-tabs" role="tablist">
									<li class="nav-item"><a class="nav-link active" id="1-tab" data-toggle="tab" href="#tab-1" role="tab" aria-controls="tab-1" aria-selected="true">NEW RELEASES</a></li>

									<li class="nav-item"><a class="nav-link" id="2-tab" data-toggle="tab" href="#tab-2" role="tab" aria-controls="tab-2" aria-selected="false">MOVIES</a></li>

									<li class="nav-item"><a class="nav-link" id="3-tab" data-toggle="tab" href="#tab-3" role="tab" aria-controls="tab-3" aria-selected="false">TV SERIES</a></li>

									<li class="nav-item"><a class="nav-link" id="4-tab" data-toggle="tab" href="#tab-4" role="tab" aria-controls="tab-4" aria-selected="false">CARTOONS</a></li>
								</ul>
							</div>
						</div>
						<!-- end content mobile tabs nav -->
					</div>
				</div>
			</div>
		</div>

		<div class="container">
			<!-- content tabs -->
			<div class="tab-content" id="myTabContent">
				<div class="tab-pane fade show active" id="tab-1" role="tabpanel" aria-labelledby="1-tab">
					<div class="row">
						<!-- card -->
                        {% for movie in films %}
						    <div class="col-6 col-sm-12 col-lg-6">
							<div class="card card--list">
								<div class="row">
									<div class="col-12 col-sm-4">
										<div class="card__cover">
											<img src="{{ movie.poster.url }}" alt="">
											<a href="{{ movie.get_absolute_url }}" class="card__play">
												<i class="icon ion-ios-play"></i>
											</a>
										</div>
									</div>

									<div class="col-12 col-sm-8">
										<div class="card__content">
											<h3 class="card__title"><a href="{{ movie.get_absolute_url }}">{{ movie.title }}</a></h3>
											<span class="card__category">
												{% for genre in movie.genre.all %}
                                                    <a href="{% url 'films:films_catalog_genre' genre.id movie.category.slug %}">{{ genre.title }}</a>
                                                {% endfor %}
											</span>

											<div class="card__wrap">
												<span class="card__rate"><i class="icon ion-ios-star"></i>{{ movie.get_average_rating }}</span>

												<ul class="card__list">
													<li>HD</li>
												</ul>
											</div>

											<div class="card__description">
												<p>{{ movie.plot }}</p>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
                        {% endfor %}
						<!-- end card -->
					</div>
				</div>

				<div class="tab-pane fade" id="tab-2" role="tabpanel" aria-labelledby="2-tab">
					<div class="row">
						<!-- card -->
                        {% for short_movie in short_movies %}
						    <div class="col-6 col-sm-12 col-lg-6">
							<div class="card card--list">
								<div class="row">
									<div class="col-12 col-sm-4">
										<div class="card__cover">
											<img src="{{ short_movie.poster.url }}" alt="">
											<a href="{{ short_movie.get_absolute_url }}" class="card__play">
												<i class="icon ion-ios-play"></i>
											</a>
										</div>
									</div>

									<div class="col-12 col-sm-8">
										<div class="card__content">
											<h3 class="card__title"><a href="{{ short_movie.get_absolute_url }}">{{ short_movie.title }}</a></h3>
											<span class="card__category">
												{% for genre in short_movie.genre.all %}
                                                    <a href="{% url 'films:films_catalog_genre' genre.id short_movie.category.slug %}">{{ genre.title }}</a>
                                                {% endfor %}
											</span>

											<div class="card__wrap">
												<span class="card__rate"><i class="icon ion-ios-star"></i>{{ short_movie.get_average_rating }}</span>

												<ul class="card__list">
													<li>HD</li>
												</ul>
											</div>

											<div class="card__description">
												<p>{{ short_movie.plot }}</p>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
                        {% endfor %}
						<!-- end card -->
					</div>
				</div>

				<div class="tab-pane fade" id="tab-3" role="tabpanel" aria-labelledby="3-tab">
					<div class="row">
						<!-- card -->
                        {% for documentary in documentaries %}
						    <div class="col-6 col-sm-12 col-lg-6">
							<div class="card card--list">
								<div class="row">
									<div class="col-12 col-sm-4">
										<div class="card__cover">
											<img src="{{ documentary.poster.url }}" alt="">
											<a href="{{ documentary.get_absolute_url }}" class="card__play">
												<i class="icon ion-ios-play"></i>
											</a>
										</div>
									</div>

									<div class="col-12 col-sm-8">
										<div class="card__content">
											<h3 class="card__title"><a href="{{ documentary.get_absolute_url }}">{{ documentary.title }}</a></h3>
											<span class="card__category">
												{% for genre in documentary.genre.all %}
                                                    <a href="{% url 'films:films_catalog_genre' genre.id documentary.category.slug %}">{{ genre.title }}</a>
                                                {% endfor %}
											</span>

											<div class="card__wrap">
												<span class="card__rate"><i class="icon ion-ios-star"></i>{{ docymentary.get_average_rating }}</span>

												<ul class="card__list">
													<li>HD</li>
												</ul>
											</div>

											<div class="card__description">
												<p>{{ documentary.plot }}</p>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
                        {% endfor %}
						<!-- end card -->
					</div>
				</div>

				<div class="tab-pane fade" id="tab-4" role="tabpanel" aria-labelledby="4-tab">
					<div class="row">
						<!-- card -->
                        {% for cartoon in cartoons %}
						    <div class="col-6 col-sm-12 col-lg-6">
							<div class="card card--list">
								<div class="row">
									<div class="col-12 col-sm-4">
										<div class="card__cover">
											<img src="{{ cartoon.poster.url }}" alt="">
											<a href="{{ cartoon.get_absolute_url }}" class="card__play">
												<i class="icon ion-ios-play"></i>
											</a>
										</div>
									</div>

									<div class="col-12 col-sm-8">
										<div class="card__content">
											<h3 class="card__title"><a href="{{ cartoon.get_absolute_url }}">{{ cartoon.title }}</a></h3>
											<span class="card__category">
												{% for genre in cartoon.genre.all %}
                                                    <a href="{% url 'films:films_catalog_genre' genre.id cartoon.category.slug %}">{{ genre.title }}</a>
                                                {% endfor %}
											</span>

											<div class="card__wrap">
												<span class="card__rate"><i class="icon ion-ios-star"></i>{{ cartoon.get_average_rating }}</span>

												<ul class="card__list">
													<li>HD</li>
												</ul>
											</div>

											<div class="card__description">
												<p>{{ cartoon.plot }}</p>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
                        {% endfor %}
						<!-- end card -->
					</div>
				</div>
			</div>
			<!-- end content tabs -->
		</div>
	</section>
	<!-- end content -->

	<!-- expected premiere -->
	{% include 'include/expected_premiere.html' %}
	<!-- end expected premiere -->

	<!-- partners -->
	{% include 'include/partners.html' %}
	<!-- end partners -->
{% endblock content %}

templates/pages/temp.html
<a data-fslightbox="gallery" data-type="image" href="img/photo-gallery-1.jpg" class="gallery__item gallery__item-1">
    <picture>
        <source class="gallery__img" type="image/webp" srcset="img/photo-gallery-1.webp">
        <img src="img/photo-gallery-1.jpg" class="gallery__img" alt="">
	</picture>
</a>