films/urls.py
from django.urls import path
from . import views

app_name = 'films'

urlpatterns = [
    path('', views.home_page, name='home'),
    path('filter/', views.filter_films, name='filter_films'),
    path('<slug:category_slug>', views.film_list_category, name='films_catalog_category'),
    path('genre/<int:pk>/<str:slug>', views.film_list_genre, name='films_catalog_genre'),
    path('review/<slug:film_slug>/', views.add_review_or_comment, name='add_review'),
    path('search-result/', views.search_result, name='search_result'),
    path('film/<slug:film_slug>', views.detail_page, name='detail_page'),
    path('about/', views.about_page, name='about'),
    path('contacts/', views.contact_page, name='contacts'),
    path('privacy/', views.privacy_page, name='privacy_policy'),
    path('delete-comment/<int:pk>/<str:slug>', views.delete_comment, name='delete_comment'),
    path('delete_review/<int:pk>/<str:slug>', views.delete_review, name='delete_review'),
    path('like_comment/', views.comments_likes_or_dislike, name='like_unlike_comment'),
    path('like_review/', views.review_likes_or_dislike, name='like_unlike_review'),
    path('selected/', views.selected_movie, name='selected_movie'),
]

portfolio_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="Photo API",
        default_version="v1",
        description="Displaying Movies from authorsFilmsFlixGo portfolio",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="kirkevich.anton@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny, ],
)


urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('api/v1/', include('apimovie.urls')),
    path('api/v1/dj-rest-auth/', include('dj_rest_auth.urls')),
    path('api/v1/dj-rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path("", include("films.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/catalogs/films_catalog.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
AFFG Catalog
{% endblock title %}
{% block content %}
	<!-- page title -->
	<section class="section section--first section--bg" data-bg="{% static 'img/section/section.jpg' %}">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="section__wrap">
						<!-- section title -->
						<h2 class="section__title">
                            {% if selected_genre.title %}
                                Genre: {{ selected_genre.title|title }}
                            {% else %}
                                Category: {{ selected.title|title  }}
                            {% endif %}
                        </h2>
						<!-- end section title -->

						<!-- breadcrumb -->
						<ul class="breadcrumb">
							<li class="breadcrumb__item"><a href="{% url 'films:home' %}">Home</a></li>
							<li class="breadcrumb__item breadcrumb__item--active">{{ selected.title }}</li>
						</ul>
						<!-- end breadcrumb -->
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- end page title -->

	<!-- filter -->
    <form action="{% url 'films:filter_films' %}" method="get">
        {% csrf_token %}
        <div class="filter">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="filter__content">
                            <div class="filter__items">
                                <!-- filter item -->
                                <div class="filter__item" id="filter__genre">
                                    <span class="filter__item-label">GENRE:</span>

                                    <div class="filter__item-btn dropdown-toggle" role="navigation" id="filter-genre" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        {% if selected_genre %}
                                            <input id="get_genre" type="button" value="{{ selected_genre.title }}">
                                        {% else %}
                                            <input id="get_genre" type="button" value="{{ genres.first.title }}">
                                        {% endif %}
                                        <input id="pass_genre" type="hidden" name="selected_genre">
                                        <span></span>
                                    </div>

                                    <ul class="filter__item-menu dropdown-menu scrollbar-dropdown" aria-labelledby="filter-genre">
                                        {% for genre in genres %}
                                            <li>{{ genre }}</li>
                                        {% endfor %}
                                    </ul>
                                </div>
                                <!-- end filter item -->

                                <!-- filter item -->
                                <div class="filter__item" id="filter__rate">
                                    <span class="filter__item-label">Rating:</span>

                                    <div class="filter__item-btn dropdown-toggle" role="button" id="filter-rate" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <div class="filter__range">
                                            <div id="filter__imbd-start"></div>
                                            <div id="filter__imbd-end"></div>
                                        </div>
                                        <input id="pass_start" type="hidden" name="ratings_start" value="0.0">
                                        <input id="pass_end" type="hidden" name="ratings_end" value="10.0">
                                        <span></span>
                                    </div>

                                    <div class="filter__item-menu filter__item-menu--range dropdown-menu" aria-labelledby="filter-rate">
                                        <div id="filter__imbd"></div>
                                    </div>
                                </div>
                                <!-- end filter item -->

                                <!-- filter item -->
                                <div class="filter__item" id="filter__year">
                                    <span class="filter__item-label">RELEASE YEAR:</span>

                                    <div class="filter__item-btn dropdown-toggle" role="button" id="filter-year" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <div class="filter__range">
                                            <div id="filter__years-start"></div>
                                            <div id="filter__years-end"></div>
                                        </div>
                                        <input id="start_years" type="hidden" name="years_start">
                                        <input id="end_years" type="hidden" name="years_end">
                                        <span></span>
                                    </div>

                                    <div class="filter__item-menu filter__item-menu--range dropdown-menu" aria-labelledby="filter-year">
                                        <div id="filter__years"></div>
                                    </div>
                                </div>
                                <!-- end filter item -->
                            </div>

                            <input type="hidden" name="selected" value="{{ selected.id }}">
                            <!-- filter btn -->
                            <button onclick="addValues()" class="filter__btn" type="submit">apply filter</button>
                            <!-- end filter btn -->

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
	<!-- end filter -->

	<!-- catalog -->
	<div class="catalog">
		<div class="container">
			<div class="row">
				<!-- card -->
                {% if not page_obj %}
                        <h1>Sorry no result were find</h1>
                {% endif %}
                {% for film in page_obj  %}
				    <div class="col-6 col-sm-12 col-lg-6">
					<div class="card card--list">
						<div class="row">
							<div class="col-12 col-sm-4">
								<div class="card__cover">
									<img src="{{ film.poster.url }}" alt="">
									<a href="{{ film.get_absolute_url }}" class="card__play">
										<i class="icon ion-ios-play"></i>
									</a>
								</div>
							</div>

							<div class="col-12 col-sm-8">
								<div class="card__content">
									<h3 class="card__title"><a href="{{ film.get_absolute_url }}">{{ film.title }}</a></h3>
									<span class="card__category">
										{% for genre in film.genre.all %}
                                            <a href="{% url 'films:films_catalog_genre' genre.id selected.slug %}">{{ genre.title }}</a>
                                        {% endfor %}
									</span>

									<div class="card__wrap">
										<span class="card__rate"><i class="icon ion-ios-star"></i>{{ film.get_average_rating }}</span>

										<ul class="card__list">
											<li>HD</li>
										</ul>
									</div>

									<div class="card__description">
										<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
                {% endfor %}
				<!-- end card -->

				<!-- paginator -->
                {% include 'include/pagination.html' %}
				<!-- end paginator -->
			</div>
		</div>
	</div>
	<!-- end catalog -->

	<!-- expected premiere -->
	{% include 'include/expected_premiere.html' %}
	<!-- end expected premiere -->

    <script>
        let StartYearSearch = {{ year_min|escapejs }};
        let EndYearSearch = {{ year_max|escapejs }};

        function addValues(){
            let getGenre = document.getElementById('get_genre').value;
            document.getElementById('pass_genre').value = getGenre;

            let getStart = document.getElementById('filter__imbd-start').innerText;
            document.getElementById('pass_start').value = getStart;

            let getEnd = document.getElementById('filter__imbd-end').innerText;
            document.getElementById('pass_end').value = getEnd;

            let startYear = document.getElementById('filter__years-start').innerText;
            document.getElementById('start_years').value = startYear;

            let endYear = document.getElementById('filter__years-end').innerText;
            document.getElementById('end_years').value = endYear;
        }
    </script>
{% endblock content %}

templates/catalogs/result_catalog.html
{% extends 'base.html' %}
{% block title %}Search Result{% endblock title %}
{% block content %}
	<!-- page title -->
	<section style="margin-bottom: 50px;" class="section section--first section--bg">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="section__wrap">
						<!-- section title -->
						<h2 class="section__title">Search Result</h2>
						<!-- end section title -->

						<!-- breadcrumb -->
						<ul class="breadcrumb">
							<li class="breadcrumb__item"><a href="#">Home</a></li>
							<li class="breadcrumb__item breadcrumb__item--active">Search Result</li>
						</ul>
						<!-- end breadcrumb -->
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- end page title -->


	<!-- catalog -->
	<div class="catalog">
		<div class="container">
			<div class="row">
				<!-- card -->
                {% if page_obj %}
                    {% for movie in page_obj %}
                        <div class="col-6 col-sm-4 col-lg-3 col-xl-2">
                            <div class="card">
                                <div class="card__cover">
                                    <img src="{{ movie.poster.url  }}" alt="">
                                    <a href="{{ movie.get_absolute_url }}" class="card__play">
                                        <i class="icon ion-ios-play"></i>
                                    </a>
                                </div>
                                <div class="card__content">
                                    <h3 class="card__title"><a href="#">{{ movie.title }}</a></h3>
                                    <span class="card__category">
                                        {% for genre in movie.genre.all %}
                                            <a href="{% url 'films:films_catalog_genre' genre.id movie.category.slug %}">{{ genre.title }}</a>
                                        {% endfor %}
                                    </span>
                                    <span class="card__rate"><i class="icon ion-ios-star"></i>{{ movie.get_average_rating }}</span>
                                </div>
                            </div>
                        </div>
                            <!-- end card -->
                    {% endfor %}
                {% elif result_actors %}
                    {% for actor in result_actors %}
                        <div class="col-6 col-sm-4 col-lg-3 col-xl-2">
                            <div class="card">
                                <div class="card__cover">
                                    <img src="{{ actor.photo.url }}" alt="">
                                    <a href="#" class="card__play">
                                        <i class="icon ion-ios-play"></i>
                                    </a>
                                </div>
                                <div class="card__content">
                                    <h3 class="card__title"><a href="#">{{ actor.name }}</a></h3>
                                    <span class="card__category">
                                        <a href="#">Action</a>
                                        <a href="#">Triler</a>
                                    </span>
                                    <span class="card__rate"><i class="icon ion-ios-star"></i>8.4</span>
                                </div>
                            </div>
                        </div>
                            <!-- end card -->
                    {% endfor %}
                {% else %}
                    <h2>{{ message }}</h2>
                {% endif %}
				<!-- end card -->

                <!-- paginator -->
                {% include 'include/pagination_result.html' %}
				<!-- end paginator -->
			</div>
		</div>
	</div>
	<!-- end catalog -->

{% endblock content %}