films/urls.py
from django.urls import path
from . import views

app_name = 'films'

urlpatterns = [
    path('', views.home_page, name='home'),
    path('filter/', views.filter_films, name='filter_films'),
    path('<slug:category_slug>', views.film_list_category, name='films_catalog_category'),
    path('genre/<int:pk>/<str:slug>', views.film_list_genre, name='films_catalog_genre'),
    path('review/<slug:film_slug>/', views.add_review_or_comment, name='add_review'),
    path('search-result/', views.search_result, name='search_result'),
    path('film/<slug:film_slug>', views.detail_page, name='detail_page'),
    path('about/', views.about_page, name='about'),
    path('contacts/', views.contact_page, name='contacts'),
    path('privacy/', views.privacy_page, name='privacy_policy'),
    path('delete-comment/<int:pk>/<str:slug>', views.delete_comment, name='delete_comment'),
    path('delete_review/<int:pk>/<str:slug>', views.delete_review, name='delete_review'),
    path('like_comment/', views.comments_likes_or_dislike, name='like_unlike_comment'),
    path('like_review/', views.review_likes_or_dislike, name='like_unlike_review'),
    path('selected/', views.selected_movie, name='selected_movie'),
]

portfolio_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="Photo API",
        default_version="v1",
        description="Displaying Movies from authorsFilmsFlixGo portfolio",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="kirkevich.anton@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny, ],
)


urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('api/v1/', include('apimovie.urls')),
    path('api/v1/dj-rest-auth/', include('dj_rest_auth.urls')),
    path('api/v1/dj-rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path("", include("films.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{% load category_tag %}
{% load social_share %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- CSS -->
	<link rel="stylesheet" href="{% static 'css/bootstrap-reboot.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/nouislider.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/plyr.css' %}">
	<link rel="stylesheet" href="{% static 'css/photoswipe.css' %}">
	<link rel="stylesheet" href="{% static 'css/default-skin.css' %}">
{#	<link rel="stylesheet" href="{% static 'css/popup.css' %}">#}
	<link rel="stylesheet" href="{% static 'css/main.css' %}">

	<!-- Favicons -->
	<link rel="icon" type="image/png" href="{% static 'icon/favicon-32x32.png' %}" sizes="32x32">
	<link rel="apple-touch-icon" href="{% static 'icon/favicon-32x32.png' %}">

	<meta name="description" content="">
	<meta name="keywords" content="">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

	<title>{% block title %}AFFG{% endblock title %}</title>

</head>

<body class="body">

	<!-- header -->
	<header class="header">
		<div class="header__wrap">
			<div class="container">
				<div class="row">
					<div class="col-12">
						<div class="header__content">

							<!-- header logo -->
							<a href="{% url 'films:home' %}" class="header__logo">
								<img src="{% static 'img/logo.png' %}" alt="">
							</a>
							<!-- end header logo -->

							<!-- header nav -->
							<ul class="header__nav">
								<!-- dropdown -->
								<li class="header__nav-item">
									<a href="{% url 'films:home' %}" class="header__nav-link">Home</a>
								</li>
								<!-- end dropdown -->

								<!-- dropdown -->
								<li class="header__nav-item">
									<a class="dropdown-toggle header__nav-link" href="#" role="button" id="dropdownMenuCatalog" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Catalog&nbsp;&nbsp;<span class="iconify-inline" data-icon="ion:chevron-down"></span></a>

									<ul class="dropdown-menu header__dropdown-menu" aria-labelledby="dropdownMenuCatalog">
                                        {% category_list as category_list %}
                                        {% for category in category_list %}
                                            <li><a href="{{ category.get_absolute_url }}">{{ category.title }}</a></li>
                                        {% endfor %}
									</ul>
								</li>
								<!-- end dropdown -->

								<li class="header__nav-item">
									<a href="{% url 'films:about' %}" class="header__nav-link">About</a>
								</li>

								<li class="header__nav-item">
									<a href="{% url 'films:contacts' %}" class="header__nav-link">Contact</a>
								</li>

							</ul>
							<!-- end header nav -->

							<!-- header auth -->
							<div class="header__auth">
								<button class="header__search-btn" type="button">
									<i class="icon ion-ios-search"></i>
								</button>

								<!-- dropdown -->
{#								<div class="dropdown header__lang">#}
{#									<a class="dropdown-toggle header__nav-link" href="#" role="button" id="dropdownMenuLang" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">EN *</a>#}
{##}
{#									<ul class="dropdown-menu header__dropdown-menu" aria-labelledby="dropdownMenuLang">#}
{#										<li><a href="#">English</a></li>#}
{#										<li><a href="#">Spanish</a></li>#}
{#										<li><a href="#">Russian</a></li>#}
{#									</ul>#}
{#								</div>#}
								<!-- end dropdown -->
                                {% if request.user.is_authenticated %}
                                    <a href="{% url 'profile' %}" class="header__sign-in">
                                        <i class="icon ion-ios-log-in"></i>
                                        <span>{{ request.user.username|truncatechars:11 }}</span>
                                    </a>
                                {% else %}
                                    <a href="{% url 'signin' %}" class="header__sign-in">
                                        <i class="icon ion-ios-log-in"></i>
                                        <span>sign in</span>
                                    </a>
                                {% endif %}
							</div>
							<!-- end header auth -->

							<!-- header menu btn -->
							<button class="header__btn" type="button">
								<span></span>
								<span></span>
								<span></span>
							</button>
							<!-- end header menu btn -->
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- header search -->
		<form method=POST action="{% url 'films:search_result' %}" class="header__search" >
            {% csrf_token %}
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <div class="header__search-content">
                                <input type="search" placeholder="Search for a movie, or Actors you are looking for"
                                       name="search_query">

                                <button type="submit">search</button>
                            </div>
                        </div>
                    </div>
                </div>
		</form>
		<!-- end header search -->
	</header>
	<!-- end header -->
    {% block content %}
    {% endblock content %}
	<!-- footer -->
	<footer class="footer">
		<div class="container">
			<div class="row">
				<!-- footer list -->
				<div class="col-12 col-md-3">
					<h6 class="footer__title">Download Our App</h6>
					<ul class="footer__app">
						<li><a href="#"><img src="{% static 'img/Download_on_the_App_Store_Badge.svg' %}" alt=""></a></li>
						<li><a href="#"><img src="{% static 'img/google-play-badge.png' %}" alt=""></a></li>
					</ul>
				</div>
				<!-- end footer list -->

				<!-- footer list -->
				<div class="col-6 col-sm-4 col-md-3">
					<h6 class="footer__title">Resources</h6>
					<ul class="footer__list">
						<li><a href="{% url 'films:about' %}">About Us</a></li>
					</ul>
				</div>
				<!-- end footer list -->

				<!-- footer list -->
				<div class="col-6 col-sm-4 col-md-3">
					<h6 class="footer__title">Legal</h6>
					<ul class="footer__list">
						<li><a href="{% url 'films:privacy_policy' %}">Privacy Policy</a></li>
					</ul>
				</div>
				<!-- end footer list -->

				<!-- footer list -->
				<div class="col-12 col-sm-4 col-md-3">
					<h6 class="footer__title">Contact</h6>
					<ul class="footer__list">
						<li><a href="tel:+15552345678">+1 555 234-5678</a></li>
						<li><a href="mailto:support@moviego.com">
authorsfilmsflixgo@gmail.com</a></li>
					</ul>
					<ul class="footer__social">
						<li class="facebook"><a href="{% post_to_facebook_url %}"><i class="icon ion-logo-facebook"></i></a></li>
						<li class="twitter"><a href="{% post_to_twitter_url "Nice web site" %}"><i class="icon ion-logo-twitter"></i></a></li>
					</ul>
				</div>
				<!-- end footer list -->

				<!-- footer copyright -->
				<div class="col-12">
					<div class="footer__copyright">

						<ul>
							<li><a href="{% url 'films:privacy_policy' %}">Terms of Use</a></li>
							<li><a href="{% url 'films:privacy_policy' %}">Privacy Policy</a></li>
						</ul>
					</div>
				</div>
				<!-- end footer copyright -->
			</div>
		</div>
	</footer>
	<!-- end footer -->

	<!-- JS -->
    <script src="https://code.iconify.design/2/2.1.0/iconify.min.js"></script>
	<script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/jquery.mousewheel.min.js' %}"></script>
	<script src="{% static 'js/jquery.mCustomScrollbar.min.js' %}"></script>
	<script src="{% static 'js/wNumb.js' %}"></script>
	<script src="{% static 'js/nouislider.min.js' %}"></script>
	<script src="{% static 'js/plyr.min.js' %}"></script>
	<script src="{% static 'js/jquery.morelines.min.js' %}"></script>
	<script src="{% static 'js/photoswipe.min.js' %}"></script>
	<script src="{% static 'js/photoswipe-ui-default.min.js' %}"></script>
{#	<script src="{% static 'js/fslightbox.js' %}"></script>#}
	<script defer src="{% static 'js/main.js' %}"></script>
</body>
</html>
{#{% include 'pages/footer.html' %} #}